DjangoSumerBlog/DjangoSumerBlog/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.index,name = "index"),
    path("about/",views.about,name = "about"),
    path('article/',include("article.urls")),
    path('user/',include("user.urls")),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoSumerBlog/article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "article"

urlpatterns = [
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('addarticle/',views.addarticle,name="addarticle"),
    path("<int:id>/",views.detail,name = "detail"),
    path('dashboard/update/<int:id>',views.update,name = "update"),
    path('dashboard/delete/<int:id>',views.delete,name = "delete"),
    path('',views.articles,name="articles"),
    path('comment/<int:id>',views.comment,name = "comment"),
]

DjangoSumerBlog/user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("register/",views.register,name = "register"),
    path("login/",views.loginUser,name = "login"),
    path("logout/",views.logoutUser,name = "logout"),
    
]

DjangoSumerBlog/templates/includes/navbar.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  
      <a class="navbar-brand" href="{% url 'index' %}">SumerBlog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'about' %}">About Us</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'article:articles' %}">Articles</a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if request.user.is_authenticated %}
             <li class="nav-item active">
            <a class="nav-link" href="{% url 'article:dashboard' %}">Dashboard</a>
            </li>
            <li class="nav-item active">
            <a class="nav-link" href="{% url 'user:logout' %}">Log Out</a>
            </li>
          {% else %}
            <li class="nav-item active">
            <a class="nav-link" href="{% url 'user:register' %}">Sign Up</a>
            </li>
            <li class="nav-item active">
            <a class="nav-link" href="{% url 'user:login' %}">Sign In</a>
            </li>
          {% endif %} 
        </ul>
      </div>
    </nav>