DjangoSumerBlog/DjangoSumerBlog/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.index,name = "index"),
    path("about/",views.about,name = "about"),
    path('article/',include("article.urls")),
    path('user/',include("user.urls")),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoSumerBlog/article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "article"

urlpatterns = [
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('addarticle/',views.addarticle,name="addarticle"),
    path("<int:id>/",views.detail,name = "detail"),
    path('dashboard/update/<int:id>',views.update,name = "update"),
    path('dashboard/delete/<int:id>',views.delete,name = "delete"),
    path('',views.articles,name="articles"),
    path('comment/<int:id>',views.comment,name = "comment"),
]

DjangoSumerBlog/user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("register/",views.register,name = "register"),
    path("login/",views.loginUser,name = "login"),
    path("logout/",views.logoutUser,name = "logout"),
    
]

DjangoSumerBlog/article/models.py
from django.db import models


# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE)
    title = models.CharField(max_length=50) #verbose_name = "Başlık"
    content = models.TextField()
    created_date = models.DateTimeField(auto_now_add = True)
    article_image = models.FileField(blank=True,null = True,verbose_name = "Add Photograph")
    def __str__(self):
        return self.title
    class Meta:
        ordering = ["-created_date"]
class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete=models.CASCADE,verbose_name = "Article",related_name = "comments")
    comment_author = models.CharField(max_length= 30,verbose_name="Name")
    comment_content = models.CharField(max_length=200,verbose_name="Comment")
    comment_date = models.DateTimeField(auto_now_add = True)
    def __str__(self):
        return self.comment_author
    class Meta:
        ordering = ["-comment_date"]

DjangoSumerBlog/article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","content","article_image"]

DjangoSumerBlog/article/views.py
from django.shortcuts import render,redirect,get_object_or_404,reverse
from .forms import ArticleForm
from django.contrib import messages
from .models import Article,Comment
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    return render(request,"index.html")
def about(request):
    return render(request,"about.html")

@login_required(login_url="user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context = {
        "articles":articles
    }
    return render(request,"dashboard.html",context)
@login_required(login_url="user:login")
def addarticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)
    if form.is_valid():
        article = form.save(commit = False)
        article.author = request.user
        article.save()
        messages.info(request,"Article Added")
        return redirect("article:dashboard")
    context = {
        "form":form
    }
    return render(request,"addarticle.html",context)
def detail(request,id):
    #article = Article.objects.filter(id = id).first()
    article = get_object_or_404(Article,id = id)
    comments = article.comments.all()
    context = {
        "article":article,
        "comments":comments
    }
    return render(request,"detail.html",context)
@login_required(login_url="user:login")
def update(request,id):
    instance_article = get_object_or_404(Article,id = id)
    article = ArticleForm(request.POST or None,request.FILES or None,instance = instance_article)
    context = {
        "article":article
    }
    if article.is_valid():
        instance_article = article.save(commit = False)
        instance_article.author = request.user
        instance_article.save()
        messages.info(request,"Article Updated")
        return redirect("article:dashboard")
    else:
        return render(request,"update.html",context)
@login_required(login_url="user:login")
def delete(request,id):
    article = get_object_or_404(Article, id = id)
    article.delete()
    messages.info(request,"Article Deleted")
    return redirect("article:dashboard")

def articles(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
    else:
        articles = Article.objects.all()
    context = {
        "articles":articles
    }
    return render(request,"articles.html",context)

def comment(request,id):
    article = get_object_or_404(Article,id = id)
    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")
        newComment = Comment(article = article,comment_author = comment_author,comment_content = comment_content)
        newComment.save()
        return redirect("../../article/" + str(id))

DjangoSumerBlog/templates/about.html
{% extends "layout.html" %}

{% block body %}
<h3>About Us</h3>
<hr>
{% endblock %}

DjangoSumerBlog/templates/addarticle.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
    <div class="col-md-6 offset-md-3">
    <h3>Add Article</h3>
    <hr>
    <form method = "POST" enctype = "multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}
    <hr>
    <button type="submit" class="btn btn-info">Add</button>
    </div>
        
    </form> 

{% endblock body %}

DjangoSumerBlog/templates/articles.html
{% extends "layout.html" %}

{% block body %}
<h3>Articles</h3>
<hr>
{% if articles %}
<form>
{% csrf_token %}
<input type="text" class ="form-control input-sm" maxlength = "64" placeholder="Search" name = "keyword">
<br>
<button type="submit" class="btn btn-info btn-sm">Search</button>
<hr>
</form>
<ul class="list-group">
  {% for article in articles %}
    <a href = "/article/{{article.id}}"><li class = "list-group-item">{{article.title}}</li></a>
  {% endfor %}
</ul>
{% else %}
<div class = "alert alert-info">Article Not Found</div>
{% endif %}

{% endblock %}

DjangoSumerBlog/templates/dashboard.html
{% extends "layout.html" %}

{% block body %}
<h3>Dashboard</h3>
<hr>
<small>Welcome, {{request.user.username}}</small>
<hr>
{% if articles %}
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Title</th>
      <th scope="col">Author</th>
      <th scope="col">Date</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    {% for article in articles %}
    <tr>
        <th scope = "row">{{article.id}}</th>
        <td><a href = "/article/{{article.id}}">{{article.title}}</a></td>
        <td>{{article.author}}</td>
        <td>{{article.created_date}}</td>
        <td><a href="delete/{{article.id}}"><button type="submit" class="btn btn-info">Delete</button></a></td>
        <td><a href="update/{{article.id}}"><button type="submit" class="btn btn-info">Update</button></a></td>
    </tr>
    {% endfor %}
   </tbody>
</table>
{% else %}
<div class = "alert alert-info">There is not any article</div>
{% endif %}
<hr>
<a href = "/article/addarticle" class = "btn btn-info">Add Article</a>
{% endblock %}

DjangoSumerBlog/templates/detail.html
{% extends "layout.html" %}

{% block body %}
<div class="row">

    <!-- Post Content Column -->
    <div class="col-lg-8">

      <!-- Title -->
      <h3 class="mt-4">{{article.title}}</h3>
      <hr>
      <!-- Author -->
      <p class="lead">
        By {{article.author}}
      </p>
      <hr>
      <!-- Date/Time -->
      <p>{{article.created_date}}</p>
      <hr>
      

      <!-- Preview Image -->
      {% if article.article_image %}
      <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
      {% endif %}
      <hr>
      <!-- Post Content -->
        <p class="lead">
            {{article.content|safe}}
        </p>
        <hr>
        {% if comments %}
          <h4>Comments</h4>
          <hr>
          {% for comment in comments  %}
            <div class="media mb-4">
          <div class="media-body">
            <h5 class="mt-0">{{comment.comment_author}}</h5>
            {{comment.comment_date}} <br>
            {{comment.comment_content}}
          </div>
        </div>    
        
          {% endfor %}
        {% else %}
          <div class = "alert alert-info">No Comment</div>
        {% endif %}
 
        <hr>
    
      <div class="card my-4">
          <h5 class="card-header">Leave A Comment:</h5>
          <div class="card-body">
            <form method = "post" action = "{% url 'article:comment' article.id %}">
              {% csrf_token %}
              <div class="form-group">
                  <label for="formGroupExampleInput">Name</label>
                  <input name = "comment_author" type="text" class="form-control" id="formGroupExampleInput" placeholder="İsminizi girin">
                </div>
              <div class="form-group">
                  <label for="formGroupExampleInput">Comment</label>
                <textarea name = "comment_content" class="form-control" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-info">Add Comment</button>
            </form>
          </div>
        </div>
 


      </div>
 
    </div>


      

{% endblock body %}

DjangoSumerBlog/templates/index.html
{% extends "layout.html" %}

{% block body %}
<div class = "jumbotron text-center">
    <h3>Welcome to SumerBlog</h3>
    <p>Python Django Template Blog</p>
</div>
{% endblock %}

DjangoSumerBlog/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>SumerBlog</title>
</head>
<body>
    {% include "includes/navbar.html"%}
    <br><br><br>
    <div class = "container",style = "margin-bottom: 100px">
     {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
    {% endfor %}
    
    {% endif %}
    {% block body %}
    
    {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdn.ckeditor.com/4.19.0/standard/ckeditor.js"></script>
    <script>CKEDITOR.replace( 'content',{allowedContent : true} );</script>
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
</body>
</html>

DjangoSumerBlog/templates/login.html
{% extends "layout.html" %}

{% block body %}
    {% load crispy_forms_tags %}
    <div class="col-md-6 offset-md-3">
    <h3>Sign In</h3>
    <hr>
    <form method = "POST">
    {% csrf_token %}
    {{form|crispy}}
    <hr>
    <button type = "submit" class = "btn btn-info">Login</button>
    </div>
        
    </form> 
{% endblock body %}

DjangoSumerBlog/templates/register.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
    <div class="col-md-6 offset-md-3">
    <h3>Sign Up</h3>
    <hr>    
    <form method = "POST">
        {% csrf_token %}
        {{form|crispy}}
        <hr>
        <button type = "submit" class = "btn btn-info">Sign Up</button>
    </div>
    </form>
{% endblock body %}

DjangoSumerBlog/templates/update.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
    <div class="col-md-6 offset-md-3">
    <h3>Update Article</h3>
    <hr>
    <form method = "POST" enctype = "multipart/form-data">
    {% csrf_token %}
    {{article|crispy}}
    <hr>
    <button type="submit" class="btn btn-info">Update</button>
    </div>
        
    </form> 

{% endblock body %}